export const questionBank = {
    animals: [
        { question: "Con nào biết leo cây?", options: [{ text: "Con cá", icon: "🐟" }, { text: "Con khỉ", icon: "🐒" }], answer: "Con khỉ" },
        { question: "Con nào gáy 'O ó o o' vào buổi sáng?", options: [{ text: "Con gà trống", icon: "🐓" }, { text: "Con gà mái", icon: "🐔" }], answer: "Con gà trống" },
        { question: "Con nào có cái vòi rất dài?", options: [{ text: "Con voi", icon: "🐘" }, { text: "Con chó", icon: "🐕" }], answer: "Con voi" },
        { question: "Con nào nhảy rất cao và có túi trước bụng?", options: [{ text: "Con Kanguru", icon: "🦘" }, { text: "Con thỏ", icon: "🐇" }], answer: "Con Kanguru" },
        { question: "Con nào có cổ rất dài?", options: [{ text: "Hươu cao cổ", icon: "🦒" }, { text: "Con ngựa", icon: "🐎" }], answer: "Hươu cao cổ" },
        { question: "Con nào mang nhà trên lưng?", options: [{ text: "Con ốc sên", icon: "🐌" }, { text: "Con sâu", icon: "🐛" }], answer: "Con ốc sên" },
        { question: "Con nào thích ăn mật ong?", options: [{ text: "Con gấu", icon: "🐻" }, { text: "Con mèo", icon: "🐱" }], answer: "Con gấu" },
        { question: "Con nào chạy nhanh nhất?", options: [{ text: "Con báo", icon: "🐆" }, { text: "Con rùa", icon: "🐢" }], answer: "Con báo" },
        { question: "Con nào sủa gâu gâu?", options: [{ text: "Con chó", icon: "🐶" }, { text: "Con vịt", icon: "🦆" }], answer: "Con chó" },
        { question: "Con nào kêu meo meo?", options: [{ text: "Con mèo", icon: "🐱" }, { text: "Con chuột", icon: "🐭" }], answer: "Con mèo" },
        { question: "Con nào cho chúng ta sữa?", options: [{ text: "Con bò", icon: "🐄" }, { text: "Con hổ", icon: "🐅" }], answer: "Con bò" },
        { question: "Con nào có bờm thật oai phong?", options: [{ text: "Sư tử", icon: "🦁" }, { text: "Con thỏ", icon: "🐰" }], answer: "Sư tử" },
        { question: "Con nào kêu quạc quạc?", options: [{ text: "Con vịt", icon: "🦆" }, { text: "Con gà", icon: "🐓" }], answer: "Con vịt" },
        { question: "Con nào thích ăn cà rốt?", options: [{ text: "Con thỏ", icon: "🐰" }, { text: "Con lợn", icon: "🐷" }], answer: "Con thỏ" },
        { question: "Con nào to nhất đại dương?", options: [{ text: "Cá voi", icon: "🐳" }, { text: "Cá vàng", icon: "🐠" }], answer: "Cá voi" },
        { question: "Con nào có bộ lông vằn?", options: [{ text: "Con hổ", icon: "🐅" }, { text: "Con báo", icon: "🐆" }], answer: "Con hổ" },
        { question: "Con nào chăm chỉ giăng tơ?", options: [{ text: "Con nhện", icon: "🕷️" }, { text: "Con kiến", icon: "🐜" }], answer: "Con nhện" },
        { question: "Con nào có nhiều chân nhất?", options: [{ text: "Con cuốn chiếu", icon: "🐛" }, { text: "Con chó", icon: "🐕" }], answer: "Con cuốn chiếu" },
        { question: "Con nào kêu ộp ộp ở ao?", options: [{ text: "Con ếch", icon: "🐸" }, { text: "Con cá", icon: "🐟" }], answer: "Con ếch" },
        { question: "Con nào có nhiều gai trên lưng?", options: [{ text: "Con nhím", icon: "🦔" }, { text: "Con thỏ", icon: "🐰" }], answer: "Con nhím" },
        { question: "Con nào nở ra từ quả trứng?", options: [{ text: "Con gà", icon: "🐣" }, { text: "Con chó", icon: "🐶" }], answer: "Con gà" },
        { question: "Con nào giúp bác nông dân cày ruộng?", options: [{ text: "Con trâu", icon: "🐃" }, { text: "Con mèo", icon: "🐱" }], answer: "Con trâu" },
        { question: "Con nào có vòi phun nước?", options: [{ text: "Con voi", icon: "🐘" }, { text: "Con ngựa", icon: "🐎" }], answer: "Con voi" },
        { question: "Con nào đuôi dài biết đánh đu?", options: [{ text: "Con khỉ", icon: "🐒" }, { text: "Con rùa", icon: "🐢" }], answer: "Con khỉ" },
        { question: "Con nào cánh mỏng màu sặc sỡ?", options: [{ text: "Con bướm", icon: "🦋" }, { text: "Con kiến", icon: "🐜" }], answer: "Con bướm" }
    ],
    nature: [
        { question: "Bầu trời ban ngày có màu gì?", options: [{ text: "Xanh da trời", icon: "☀️" }, { text: "Màu đen", icon: "🌑" }], answer: "Xanh da trời" },
        { question: "Cái gì chiếu sáng ban đêm?", options: [{ text: "Mặt trăng", icon: "🌙" }, { text: "Bóng đèn", icon: "💡" }], answer: "Mặt trăng" },
        { question: "Mưa rơi xuống từ đâu?", options: [{ text: "Đám mây", icon: "☁️" }, { text: "Cây xanh", icon: "🌳" }], answer: "Đám mây" },
        { question: "Cầu vồng có mấy màu?", options: [{ text: "7 màu", icon: "🌈" }, { text: "2 màu", icon: "⚪" }], answer: "7 màu" },
        { question: "Tuyết màu gì?", options: [{ text: "Màu trắng", icon: "❄️" }, { text: "Màu xanh", icon: "🌿" }], answer: "Màu trắng" },
        { question: "Mặt trời mọc ở hướng nào?", options: [{ text: "Hướng Đông", icon: "🌅" }, { text: "Hướng Tây", icon: "🌇" }], answer: "Hướng Đông" },
        { question: "Biển mặn hay ngọt?", options: [{ text: "Vị mặn", icon: "🌊" }, { text: "Vị ngọt", icon: "🍬" }], answer: "Vị mặn" },
        { question: "Lửa nóng hay lạnh?", options: [{ text: "Rất nóng", icon: "🔥" }, { text: "Rất lạnh", icon: "🧊" }], answer: "Rất nóng" },
        { question: "Nước đá có cảm giác gì?", options: [{ text: "Lạnh buốt", icon: "🧊" }, { text: "Nóng hổi", icon: "☕" }], answer: "Lạnh buốt" },
        { question: "Cái gì thổi làm lá cây rung rinh?", options: [{ text: "Gió", icon: "💨" }, { text: "Nước", icon: "💧" }], answer: "Gió" },
        { question: "Mùa nào nóng nhất trong năm?", options: [{ text: "Mùa hè", icon: "🏖️" }, { text: "Mùa đông", icon: "⛄" }], answer: "Mùa hè" },
        { question: "Mùa nào có tuyết rơi?", options: [{ text: "Mùa đông", icon: "❄️" }, { text: "Mùa thu", icon: "🍂" }], answer: "Mùa đông" },
        { question: "Sấm chớp thường đi cùng với gì?", options: [{ text: "Trời mưa", icon: "⛈️" }, { text: "Nắng to", icon: "🌞" }], answer: "Trời mưa" },
        { question: "Ban đêm bầu trời có gì lung linh?", options: [{ text: "Ngôi sao", icon: "⭐" }, { text: "Mặt trời", icon: "☀️" }], answer: "Ngôi sao" },
        { question: "Suối nước chảy từ đâu xuống?", options: [{ text: "Từ núi cao", icon: "⛰️" }, { text: "Từ dưới đất", icon: "🌱" }], answer: "Từ núi cao" },
        { question: "Sa mạc có rất nhiều gì?", options: [{ text: "Cát", icon: "🏜️" }, { text: "Nước", icon: "💧" }], answer: "Cát" },
        { question: "Chúng ta hít thở cái gì?", options: [{ text: "Không khí", icon: "🌬️" }, { text: "Đồ ăn", icon: "🍔" }], answer: "Không khí" },
        { question: "Cái gì hiện ra sau cơn mưa?", options: [{ text: "Cầu vồng", icon: "🌈" }, { text: "Bão tuyết", icon: "🌨️" }], answer: "Cầu vồng" },
        { question: "Rừng xanh có rất nhiều gì?", options: [{ text: "Cây xanh", icon: "🌳" }, { text: "Nhà cao tầng", icon: "🏢" }], answer: "Cây xanh" },
        { question: "Khi trời lạnh ta cần mặc gì?", options: [{ text: "Áo khoác", icon: "🧥" }, { text: "Áo bơi", icon: "🩱" }], answer: "Áo khoác" },
        { question: "Ông mặt trời đi ngủ vào lúc nào?", options: [{ text: "Buổi tối", icon: "🌙" }, { text: "Buổi sáng", icon: "🌅" }], answer: "Buổi tối" },
        { question: "Đất dùng để làm gì?", options: [{ text: "Trồng cây", icon: "🌳" }, { text: "Để uống", icon: "🍹" }], answer: "Trồng cây" },
        { question: "Song biển vỗ vào đâu?", options: [{ text: "Bờ cát", icon: "🏖️" }, { text: "Mái nhà", icon: "🏠" }], answer: "Bờ cát" },
        { question: "Hạt mưa có hình gì?", options: [{ text: "Giọt nước", icon: "💧" }, { text: "Hình vuông", icon: "⏹️" }], answer: "Giọt nước" },
        { question: "Cái gì giúp thắp sáng ban ngày?", options: [{ text: "Mặt trời", icon: "🌞" }, { text: "Ngọn đèn", icon: "🕯️" }], answer: "Mặt trời" }
    ],
    plants: [
        { question: "Quả gì màu đỏ hạt nhỏ li ti?", options: [{ text: "Dâu tây", icon: "🍓" }, { text: "Chuối", icon: "🍌" }], answer: "Dâu tây" },
        { question: "Súp lơ có màu gì?", options: [{ text: "Màu xanh", icon: "🥦" }, { text: "Màu đỏ", icon: "🎈" }], answer: "Màu xanh" },
        { question: "Quả chuối có dáng hình gì?", options: [{ text: "Cong cong", icon: "🍌" }, { text: "Tròn xoe", icon: "⚽" }], answer: "Cong cong" },
        { question: "Lá cây thường có màu gì?", options: [{ text: "Màu xanh", icon: "🍃" }, { text: "Màu hồng", icon: "🌸" }], answer: "Màu xanh" },
        { question: "Cây cần gì để sống?", options: [{ text: "Nước", icon: "💧" }, { text: "Bánh kẹo", icon: "🍭" }], answer: "Nước" },
        { question: "Hoa hồng thường có gì ở cành?", options: [{ text: "Gai nhọn", icon: "🥀" }, { text: "Lông vũ", icon: "🪶" }], answer: "Gai nhọn" },
        { question: "Quả dưa hấu lòng màu gì?", options: [{ text: "Màu đỏ", icon: "🍉" }, { text: "Màu xanh", icon: "🧊" }], answer: "Màu đỏ" },
        { question: "Hạt dẻ là món khoái khẩu của ai?", options: [{ text: "Con sóc", icon: "🐿️" }, { text: "Con cá", icon: "🐟" }], answer: "Con sóc" },
        { question: "Củ cà rốt mọc ở đâu?", options: [{ text: "Dưới đất", icon: "🥕" }, { text: "Trên trời", icon: "☁️" }], answer: "Dưới đất" },
        { question: "Quả khế có mấy khía?", options: [{ text: "5 khía", icon: "🌟" }, { text: "1 khía", icon: "☝️" }], answer: "5 khía" },
        { question: "Hoa sen sống ở đâu?", options: [{ text: "Dưới hồ", icon: "🪷" }, { text: "Trên núi", icon: "⛰️" }], answer: "Dưới hồ" },
        { question: "Quả táo chín có màu gì?", options: [{ text: "Màu đỏ", icon: "🍎" }, { text: "Màu tím", icon: "🍇" }], answer: "Màu đỏ" },
        { question: "Quả nho mọc theo gì?", options: [{ text: "Từng chùm", icon: "🍇" }, { text: "Từng củ", icon: "🥔" }], answer: "Từng chùm" },
        { question: "Cây dừa thường mọc ở đâu?", options: [{ text: "Bãi biển", icon: "🏖️" }, { text: "Trong lớp", icon: "🏫" }], answer: "Bãi biển" },
        { question: "Quả xoài chín có vị gì?", options: [{ text: "Ngọt", icon: "🥭" }, { text: "Cay", icon: "🌶️" }], answer: "Ngọt" },
        { question: "Hoa đào nở vào dịp nào?", options: [{ text: "Ngày Tết", icon: "🌸" }, { text: "Trung thu", icon: "🥮" }], answer: "Ngày Tết" },
        { question: "Quả dứa (thơm) có rất nhiều gì?", options: [{ text: "Mắt dứa", icon: "🍍" }, { text: "Tai", icon: "👂" }], answer: "Mắt dứa" },
        { question: "Cây xương rồng có nhiều gì?", options: [{ text: "Gai", icon: "🌵" }, { text: "Lá to", icon: "🌱" }], answer: "Gai" },
        { question: "Quả bưởi to hay nhỏ?", options: [{ text: "To", icon: "🍈" }, { text: "Rất nhỏ", icon: "🍒" }], answer: "To" },
        { question: "Quả ớt có vị gì?", options: [{ text: "Vị cay", icon: "🌶️" }, { text: "Vị ngọt", icon: "🍦" }], answer: "Vị cay" },
        { question: "Quả chanh có vị gì?", options: [{ text: "Vị chua", icon: "🍋" }, { text: "Vị mặn", icon: "🧂" }], answer: "Vị chua" },
        { question: "Quả mít có vỏ như thế nào?", options: [{ text: "Có gai", icon: "🍈" }, { text: "Mềm mịn", icon: "🍑" }], answer: "Có gai" },
        { question: "Cây tre có thân như thế nào?", options: [{ text: "Thẳng đứng", icon: "🎋" }, { text: "Bò dưới đất", icon: "🪵" }], answer: "Thẳng đứng" },
        { question: "Quả đu đủ chín lòng màu gì?", options: [{ text: "Màu cam", icon: "🥭" }, { text: "Màu trắng", icon: "🍚" }], answer: "Màu cam" },
        { question: "Quả bắp (ngô) có hạt màu gì?", options: [{ text: "Màu vàng", icon: "🌽" }, { text: "Màu xanh", icon: "🥬" }], answer: "Màu vàng" }
    ],
    landmarks: [
        { question: "Thủ đô của Việt Nam là gì?", options: [{ text: "Hà Nội", icon: "🏙️" }, { text: "Sài Gòn", icon: "🌆" }], answer: "Hà Nội" },
        { question: "Tháp Eiffel nằm ở nước nào?", options: [{ text: "Pháp", icon: "🇫🇷" }, { text: "Mỹ", icon: "🇺🇸" }], answer: "Pháp" },
        { question: "Hồ Gươm nằm ở thành phố nào?", options: [{ text: "Hà Nội", icon: "🏯" }, { text: "Cần Thơ", icon: "🌉" }], answer: "Hà Nội" },
        { question: "Chùa Một Cột trông giống bông hoa gì?", options: [{ text: "Hoa sen", icon: "🪷" }, { text: "Hoa lan", icon: "🌸" }], answer: "Hoa sen" },
        { question: "Máy bay bay ở đâu?", options: [{ text: "Trên trời", icon: "✈️" }, { text: "Dưới nước", icon: "🛥️" }], answer: "Trên trời" },
        { question: "Ô tô chạy ở đâu?", options: [{ text: "Trên đường bộ", icon: "🚗" }, { text: "Trên mây", icon: "☁️" }], answer: "Trên đường bộ" },
        { question: "Thuyền chạy ở đâu?", options: [{ text: "Trên nước", icon: "⛵" }, { text: "Trên núi", icon: "⛰️" }], answer: "Trên nước" },
        { question: "Xe đạp có mấy bánh?", options: [{ text: "2 bánh", icon: "🚲" }, { text: "4 bánh", icon: "🚗" }], answer: "2 bánh" },
        { question: "Chúng ta ăn bằng gì?", options: [{ text: "Cái miệng", icon: "👄" }, { text: "Cái tai", icon: "👂" }], answer: "Cái miệng" },
        { question: "Chúng ta nhìn bằng gì?", options: [{ text: "Đôi mắt", icon: "👀" }, { text: "Bàn chân", icon: "🦶" }], answer: "Đôi mắt" },
        { question: "Chúng ta nghe bằng gì?", options: [{ text: "Đôi tai", icon: "👂" }, { text: "Cái mũi", icon: "👃" }], answer: "Đôi tai" },
        { question: "Chúng ta đi bằng gì?", options: [{ text: "Đôi chân", icon: "🦶" }, { text: "Bàn tay", icon: "✋" }], answer: "Đôi chân" },
        { question: "Trường học có ai dạy bé?", options: [{ text: "Cô giáo", icon: "👩‍🏫" }, { text: "Con mèo", icon: "🐱" }], answer: "Cô giáo" },
        { question: "Khám bệnh thì đến đâu?", options: [{ text: "Bệnh viện", icon: "🏥" }, { text: "Rạp xiếc", icon: "⛺" }], answer: "Bệnh viện" },
        { question: "Đồ chơi búp bê làm bằng gì?", options: [{ text: "Nhựa hoặc vải", icon: "🪆" }, { text: "Đá", icon: "🪨" }], answer: "Nhựa hoặc vải" },
        { question: "Đánh răng cần dùng gì?", options: [{ text: "Bàn chải", icon: "🪥" }, { text: "Cái thìa", icon: "🥄" }], answer: "Bàn chải" },
        { question: "Rửa tay giúp chúng ta làm gì?", options: [{ text: "Sạch vi khuẩn", icon: "🧼" }, { text: "Bị ốm", icon: "🤒" }], answer: "Sạch vi khuẩn" },
        { question: "Công viên có trò chơi gì?", options: [{ text: "Cầu trượt", icon: "🛝" }, { text: "Tủ lạnh", icon: "🧊" }], answer: "Cầu trượt" },
        { question: "Muốn đọc sách thì đến đâu?", options: [{ text: "Thư viện", icon: "📚" }, { text: "Nhà bếp", icon: "🍳" }], answer: "Thư viện" },
        { question: "Bưu điện dùng để làm gì?", options: [{ text: "Gửi thư", icon: "✉️" }, { text: "Để ngủ", icon: "🛌" }], answer: "Gửi thư" },
        { question: "Cầu Thê Húc có màu gì?", options: [{ text: "Màu đỏ", icon: "⛩️" }, { text: "Màu xanh", icon: "🌳" }], answer: "Màu đỏ" },
        { question: "Chợ dùng để làm gì?", options: [{ text: "Mua bán", icon: "🛍️" }, { text: "Đi tắm", icon: "🛁" }], answer: "Mua bán" },
        { question: "Lăng Bác nằm ở đâu?", options: [{ text: "Hà Nội", icon: "🏛️" }, { text: "Huế", icon: "🏯" }], answer: "Hà Nội" },
        { question: "Đồng hồ to ở Luân Đôn tên là gì?", options: [{ text: "Big Ben", icon: "🕰️" }, { text: "Đồng hồ cát", icon: "⏳" }], answer: "Big Ben" },
        { question: "Kim tự tháp ở nước nào?", options: [{ text: "Ai Cập", icon: "🇪🇬" }, { text: "Nhật Bản", icon: "🇯🇵" }], answer: "Ai Cập" }
    ],
    reading: [
        { question: "Đâu là chữ 🐟?", options: [{ text: "CÁ", icon: "" }, { text: "ÁC", icon: "" }], answer: "CÁ", speechPrompt: "Đâu là chữ cá" },
        { question: "Đâu là chữ 🐘?", options: [{ text: "VOI", icon: "" }, { text: "VÒI", icon: "" }], answer: "VOI", speechPrompt: "Đâu là chữ voi" },
        { question: "Đâu là chữ 🐣?", options: [{ text: "GÀ", icon: "" }, { text: "CÁ", icon: "" }], answer: "GÀ", speechPrompt: "Đâu là chữ gà" },
        { question: "Đâu là chữ 🦆?", options: [{ text: "VỊT", icon: "" }, { text: "VÍ", icon: "" }], answer: "VỊT", speechPrompt: "Đâu là chữ vịt" },
        { question: "Đâu là chữ 🐢?", options: [{ text: "RÙA", icon: "" }, { text: "RỪNG", icon: "" }], answer: "RÙA", speechPrompt: "Đâu là chữ rùa" },
        { question: "Đâu là chữ 🍎?", options: [{ text: "TÁO", icon: "" }, { text: "TẠO", icon: "" }], answer: "TÁO", speechPrompt: "Đâu là chữ táo" },
        { question: "Đâu là chữ 🍌?", options: [{ text: "CHUỐI", icon: "" }, { text: "CHUÔI", icon: "" }], answer: "CHUỐI", speechPrompt: "Đâu là chữ chuối" },
        { question: "Đâu là chữ 🍉?", options: [{ text: "DƯA", icon: "" }, { text: "DỪA", icon: "" }], answer: "DƯA", speechPrompt: "Đâu là chữ dưa" },
        { question: "Đâu là chữ 🍇?", options: [{ text: "NHO", icon: "" }, { text: "NHÀ", icon: "" }], answer: "NHO", speechPrompt: "Đâu là chữ nho" },
        { question: "Đâu là chữ 🍓?", options: [{ text: "DÂU", icon: "" }, { text: "ĐẦU", icon: "" }], answer: "DÂU", speechPrompt: "Đâu là chữ dâu" },
        { question: "Đâu là chữ 🏠?", options: [{ text: "NHÀ", icon: "" }, { text: "NHAN", icon: "" }], answer: "NHÀ", speechPrompt: "Đâu là chữ nhà" },
        { question: "Đâu là chữ 🌳?", options: [{ text: "CÂY", icon: "" }, { text: "CÁY", icon: "" }], answer: "CÂY", speechPrompt: "Đâu là chữ cây" },
        { question: "Đâu là chữ 🚲?", options: [{ text: "XE", icon: "" }, { text: "XẺ", icon: "" }], answer: "XE", speechPrompt: "Đâu là chữ xe" },
        { question: "Đâu là chữ 🌹?", options: [{ text: "HOA", icon: "" }, { text: "HÒA", icon: "" }], answer: "HOA", speechPrompt: "Đâu là chữ hoa" },
        { question: "Đâu là chữ 🧼?", options: [{ text: "XÀ PHÒNG", icon: "" }, { text: "XÀ PHONG", icon: "" }], answer: "XÀ PHÒNG", speechPrompt: "Đâu là chữ xà phòng" },
        { question: "Đâu là chữ 🎒?", options: [{ text: "CẶP", icon: "" }, { text: "CẮP", icon: "" }], answer: "CẶP", speechPrompt: "Đâu là chữ cặp" },
        { question: "Đâu là chữ ✏️?", options: [{ text: "BÚT", icon: "" }, { text: "BỤT", icon: "" }], answer: "BÚT", speechPrompt: "Đâu là chữ bút" },
        { question: "Đâu là chữ 🏫?", options: [{ text: "TRƯỜNG", icon: "" }, { text: "TRƯƠNG", icon: "" }], answer: "TRƯỜNG", speechPrompt: "Đâu là chữ trường" },
        { question: "Đâu là chữ 🦷?", options: [{ text: "RĂNG", icon: "" }, { text: "RẰNG", icon: "" }], answer: "RĂNG", speechPrompt: "Đâu là chữ răng" },
        { question: "Đâu là chữ 👂?", options: [{ text: "TAI", icon: "" }, { text: "TẠI", icon: "" }], answer: "TAI", speechPrompt: "Đâu là chữ tai" },
        { question: "Đâu là chữ 🐄?", options: [{ text: "BÒ", icon: "" }, { text: "BO", icon: "" }], answer: "BÒ", speechPrompt: "Đâu là chữ bò" },
        { question: "Đâu là chữ 🦁?", options: [{ text: "SƯ TỬ", icon: "" }, { text: "SỬ TỬ", icon: "" }], answer: "SƯ TỬ", speechPrompt: "Đâu là chữ sư tử" },
        { question: "Đâu là chữ 🦊?", options: [{ text: "CÁO", icon: "" }, { text: "CAO", icon: "" }], answer: "CÁO", speechPrompt: "Đâu là chữ cáo" },
        { question: "Đâu là chữ 🐯?", options: [{ text: "HỔ", icon: "" }, { text: "HỒ", icon: "" }], answer: "HỔ", speechPrompt: "Đâu là chữ hổ" },
        { question: "Đâu là chữ 🐻?", options: [{ text: "GẤU", icon: "" }, { text: "GẦU", icon: "" }], answer: "GẤU", speechPrompt: "Đâu là chữ gấu" },
        { question: "Đâu là chữ 🐷?", options: [{ text: "LỢN", icon: "" }, { text: "LỚN", icon: "" }], answer: "LỢN", speechPrompt: "Đâu là chữ lợn" },
        { question: "Đâu là chữ 🐀?", options: [{ text: "CHUỘT", icon: "" }, { text: "CHUỘT", icon: "" }], answer: "CHUỘT", speechPrompt: "Đâu là chữ chuột" },
        { question: "Đâu là chữ 🦒?", options: [{ text: "HƯƠU", icon: "" }, { text: "RƯỢU", icon: "" }], answer: "HƯƠU", speechPrompt: "Đâu là chữ hươu" },
        { question: "Đâu là chữ 🐝?", options: [{ text: "ONG", icon: "" }, { text: "ÔNG", icon: "" }], answer: "ONG", speechPrompt: "Đâu là chữ ong" },
        { question: "Đâu là chữ 🦋?", options: [{ text: "BƯỚM", icon: "" }, { text: "BƯƠM", icon: "" }], answer: "BƯỚM", speechPrompt: "Đâu là chữ bướm" },
        { question: "Đâu là chữ 🐜?", options: [{ text: "KIẾN", icon: "" }, { text: "KIÊN", icon: "" }], answer: "KIẾN", speechPrompt: "Đâu là chữ kiến" },
        { question: "Đâu là chữ 🕷️?", options: [{ text: "NHỆN", icon: "" }, { text: "NHÊN", icon: "" }], answer: "NHỆN", speechPrompt: "Đâu là chữ nhện" },
        { question: "Đâu là chữ 🦀?", options: [{ text: "CUA", icon: "" }, { text: "CỦA", icon: "" }], answer: "CUA", speechPrompt: "Đâu là chữ cua" },
        { question: "Đâu là chữ 🦐?", options: [{ text: "TÔM", icon: "" }, { text: "TỐM", icon: "" }], answer: "TÔM", speechPrompt: "Đâu là chữ tôm" },
        { question: "Đâu là chữ 🐚?", options: [{ text: "ỐC", icon: "" }, { text: "ÓC", icon: "" }], answer: "ỐC", speechPrompt: "Đâu là chữ ốc" },
        { question: "Đâu là chữ 🦅?", options: [{ text: "ĐẠI BÀNG", icon: "" }, { text: "ĐẠI BANG", icon: "" }], answer: "ĐẠI BÀNG", speechPrompt: "Đâu là chữ đại bàng" },
        { question: "Đâu là chữ 🦢?", options: [{ text: "THIÊN NGA", icon: "" }, { text: "THIÊN NGHÉ", icon: "" }], answer: "THIÊN NGA", speechPrompt: "Đâu là chữ thiên nga" },
        { question: "Đâu là chữ 🦜?", options: [{ text: "VẸT", icon: "" }, { text: "VE", icon: "" }], answer: "VẸT", speechPrompt: "Đâu là chữ vẹt" },
        { question: "Đâu là chữ 🦉?", options: [{ text: "CÚ", icon: "" }, { text: "CU", icon: "" }], answer: "CÚ", speechPrompt: "Đâu là chữ cú" },
        { question: "Đâu là chữ 🐧?", options: [{ text: "CÁNH CỤT", icon: "" }, { text: "CÁC CỤT", icon: "" }], answer: "CÁNH CỤT", speechPrompt: "Đâu là chữ cánh cụt" },
        { question: "Đâu là chữ 🐬?", options: [{ text: "CÁ HEO", icon: "" }, { text: "CÁ HEO", icon: "" }], answer: "CÁ HEO", speechPrompt: "Đâu là chữ cá heo" },
        { question: "Đâu là chữ 🦈?", options: [{ text: "CÁ MẬP", icon: "" }, { text: "CÁ MẬP", icon: "" }], answer: "CÁ MẬP", speechPrompt: "Đâu là chữ cá mập" },
        { question: "Đâu là chữ 🐳?", options: [{ text: "CÁ VOI", icon: "" }, { text: "CÁ VÒI", icon: "" }], answer: "CÁ VOI", speechPrompt: "Đâu là chữ cá voi" },
        { question: "Đâu là chữ 🐙?", options: [{ text: "BẠCH TUỘC", icon: "" }, { text: "BẠCH TUỘT", icon: "" }], answer: "BẠCH TUỘC", speechPrompt: "Đâu là chữ bạch tuộc" },
        { question: "Đâu là chữ 🐡?", options: [{ text: "CÁ NÓC", icon: "" }, { text: "CÁ NOC", icon: "" }], answer: "CÁ NÓC", speechPrompt: "Đâu là chữ cá nóc" },
        { question: "Đâu là chữ 🌴?", options: [{ text: "CÂY DỪA", icon: "" }, { text: "CÂY DỨA", icon: "" }], answer: "CÂY DỪA", speechPrompt: "Đâu là chữ cây dừa" },
        { question: "Đâu là chữ 🍍?", options: [{ text: "QUẢ DỨA", icon: "" }, { text: "QUẢ DỪA", icon: "" }], answer: "QUẢ DỨA", speechPrompt: "Đâu là chữ quả dứa" },
        { question: "Đâu là chữ 🥭?", options: [{ text: "QUẢ XOÀI", icon: "" }, { text: "QUẢ XOÀI", icon: "" }], answer: "QUẢ XOÀI", speechPrompt: "Đâu là chữ quả xoài" },
        { question: "Đâu là chữ 🍐?", options: [{ text: "QUẢ LÊ", icon: "" }, { text: "QUẢ LỄ", icon: "" }], answer: "QUẢ LÊ", speechPrompt: "Đâu là chữ quả lê" },
        { question: "Đâu là chữ 🍑?", options: [{ text: "QUẢ ĐÀO", icon: "" }, { text: "QUẢ ĐẢO", icon: "" }], answer: "QUẢ ĐÀO", speechPrompt: "Đâu là chữ quả đào" },
        { question: "Đâu là chữ 🍇?", options: [{ text: "QUẢ NHO", icon: "" }, { text: "QUẢ NHỜ", icon: "" }], answer: "QUẢ NHO", speechPrompt: "Đâu là chữ quả nho" },
        { question: "Đâu là chữ 🍉?", options: [{ text: "DƯA HẤU", icon: "" }, { text: "DỰA HẤU", icon: "" }], answer: "DƯA HẤU", speechPrompt: "Đâu là chữ dưa hấu" },
        { question: "Đâu là chữ 🍊?", options: [{ text: "QUẢ CAM", icon: "" }, { text: "QUẢ CÁM", icon: "" }], answer: "QUẢ CAM", speechPrompt: "Đâu là chữ quả cam" },
        { question: "Đâu là chữ 🍋?", options: [{ text: "QUẢ CHANH", icon: "" }, { text: "QUẢ CHÁNH", icon: "" }], answer: "QUẢ CHANH", speechPrompt: "Đâu là chữ quả chanh" },
        { question: "Đâu là chữ 🥕?", options: [{ text: "CÀ RỐT", icon: "" }, { text: "CÁ RỐT", icon: "" }], answer: "CÀ RỐT", speechPrompt: "Đâu là chữ cà rốt" },
        { question: "Đâu là chữ 🌽?", options: [{ text: "BẮP NGO", icon: "" }, { text: "BÁP NGÔ", icon: "" }], answer: "BẮP NGO", speechPrompt: "Đâu là chữ bắp ngô" },
        { question: "Đâu là chữ 🥔?", options: [{ text: "KHOAI TÂY", icon: "" }, { text: "KHOÁI TÂY", icon: "" }], answer: "KHOAI TÂY", speechPrompt: "Đâu là chữ khoai tây" },
        { question: "Đâu là chữ 🥦?", options: [{ text: "SÚP LƠ", icon: "" }, { text: "SUP LƠ", icon: "" }], answer: "SÚP LƠ", speechPrompt: "Đâu là chữ súp lơ" },
        { question: "Đâu là chữ 🍅?", options: [{ text: "CÀ CHUA", icon: "" }, { text: "CÁ CHUA", icon: "" }], answer: "CÀ CHUA", speechPrompt: "Đâu là chữ cà chua" },
        { question: "Đâu là chữ 🍆?", options: [{ text: "CÀ TÍM", icon: "" }, { text: "CÁ TÍM", icon: "" }], answer: "CÀ TÍM", speechPrompt: "Đâu là chữ cà tím" },
        { question: "Đâu là chữ 🧅?", options: [{ text: "HÀNH TÂY", icon: "" }, { text: "HÁNH TÂY", icon: "" }], answer: "HÀNH TÂY", speechPrompt: "Đâu là chữ hành tây" },
        { question: "Đâu là chữ 🍄?", options: [{ text: "NẤM", icon: "" }, { text: "NAM", icon: "" }], answer: "NẤM", speechPrompt: "Đâu là chữ nấm" },
        { question: "Đâu là chữ 🍞?", options: [{ text: "BÁNH MÌ", icon: "" }, { text: "BANH MÌ", icon: "" }], answer: "BÁNH MÌ", speechPrompt: "Đâu là chữ bánh mì" },
        { question: "Đâu là chữ 🍕?", options: [{ text: "PIZZA", icon: "" }, { text: "PIZA", icon: "" }], answer: "PIZZA", speechPrompt: "Đâu là chữ pizza" },
        { question: "Đâu là chữ 🍔?", options: [{ text: "HAMBURGER", icon: "" }, { text: "HAMBUR", icon: "" }], answer: "HAMBURGER", speechPrompt: "Đâu là chữ hamburger" },
        { question: "Đâu là chữ 🥪?", options: [{ text: "SANDWICH", icon: "" }, { text: "SAND", icon: "" }], answer: "SANDWICH", speechPrompt: "Đâu là chữ sandwich" },
        { question: "Đâu là chữ 🍚?", options: [{ text: "CƠM", icon: "" }, { text: "CỚM", icon: "" }], answer: "CƠM", speechPrompt: "Đâu là chữ cơm" },
        { question: "Đâu là chữ 🍜?", options: [{ text: "MÌ TÔM", icon: "" }, { text: "MI TÔM", icon: "" }], answer: "MÌ TÔM", speechPrompt: "Đâu là chữ mì tôm" },
        { question: "Đâu là chữ 🍣?", options: [{ text: "SUSHI", icon: "" }, { text: "SUSI", icon: "" }], answer: "SUSHI", speechPrompt: "Đâu là chữ sushi" },
        { question: "Đâu là chữ 🍦?", options: [{ text: "KEM", icon: "" }, { text: "KÉM", icon: "" }], answer: "KEM", speechPrompt: "Đâu là chữ kem" },
        { question: "Đâu là chữ 🍮?", options: [{ text: "BÁNH FLAN", icon: "" }, { text: "BANH FLAN", icon: "" }], answer: "BÁNH FLAN", speechPrompt: "Đâu là chữ bánh flan" },
        { question: "Đâu là chữ 🍩?", options: [{ text: "DONUT", icon: "" }, { text: "DONA", icon: "" }], answer: "DONUT", speechPrompt: "Đâu là chữ donut" },
        { question: "Đâu là chữ 🍪?", options: [{ text: "BÁNH QUY", icon: "" }, { text: "BANH QUY", icon: "" }], answer: "BÁNH QUY", speechPrompt: "Đâu là chữ bánh quy" },
        { question: "Đâu là chữ 🍫?", options: [{ text: "SOCOLA", icon: "" }, { text: "SÔCÔLA", icon: "" }], answer: "SOCOLA", speechPrompt: "Đâu là chữ socola" },
        { question: "Đâu là chữ 🍬?", options: [{ text: "KẸO", icon: "" }, { text: "KÉO", icon: "" }], answer: "KẸO", speechPrompt: "Đâu là chữ kẹo" },
        { question: "Đâu là chữ 🍭?", options: [{ text: "KẸO MÚT", icon: "" }, { text: "KÉO MÚT", icon: "" }], answer: "KẸO MÚT", speechPrompt: "Đâu là chữ kẹo mút" },
        { question: "Đâu là chữ 🍯?", options: [{ text: "MẬT ONG", icon: "" }, { text: "MẤT ONG", icon: "" }], answer: "MẬT ONG", speechPrompt: "Đâu là chữ mật ong" },
        { question: "Đâu là chữ 🥛?", options: [{ text: "SỮA", icon: "" }, { text: "SỬA", icon: "" }], answer: "SỮA", speechPrompt: "Đâu là chữ sữa" },
        { question: "Đâu là chữ 🧉?", options: [{ text: "NƯỚC TRÀ", icon: "" }, { text: "NƯỚC TRA", icon: "" }], answer: "NƯỚC TRÀ", speechPrompt: "Đâu là chữ nước trà" },
        { question: "Đâu là chữ 🧃?", options: [{ text: "NƯỚC ÉP", icon: "" }, { text: "NƯỚC ÉP", icon: "" }], answer: "NƯỚC ÉP", speechPrompt: "Đâu là chữ nước ép" },
        { question: "Đâu là chữ 🏠?", options: [{ text: "NGÔI NHÀ", icon: "" }, { text: "NGÔI NHÁ", icon: "" }], answer: "NGÔI NHÀ", speechPrompt: "Đâu là chữ ngôi nhà" },
        { question: "Đâu là chữ 🚪?", options: [{ text: "CÁI CỬA", icon: "" }, { text: "CÁI CỬA", icon: "" }], answer: "CÁI CỬA", speechPrompt: "Đâu là chữ cái cửa" },
        { question: "Đâu là chữ 🪟?", options: [{ text: "CỬA SỔ", icon: "" }, { text: "CỬA SỐ", icon: "" }], answer: "CỬA SỔ", speechPrompt: "Đâu là chữ cửa sổ" },
        { question: "Đâu là chữ 🛏️?", options: [{ text: "CÁI DƯỜNG", icon: "" }, { text: "CÁI GIƯỜNG", icon: "" }], answer: "CÁI GIƯỜNG", speechPrompt: "Đâu là chữ cái giường" },
        { question: "Đâu là chữ 🛋️?", options: [{ text: "GHẾ SOFA", icon: "" }, { text: "GHẾ SOFA", icon: "" }], answer: "GHẾ SOFA", speechPrompt: "Đâu là chữ ghế sofa" },
        { question: "Đâu là chữ 📺?", options: [{ text: "TIVI", icon: "" }, { text: "TIVI", icon: "" }], answer: "TIVI", speechPrompt: "Đâu là chữ tivi" },
        { question: "Đâu là chữ 💻?", options: [{ text: "MÁY TÍNH", icon: "" }, { text: "MÀY TÍNH", icon: "" }], answer: "MÁY TÍNH", speechPrompt: "Đâu là chữ máy tính" },
        { question: "Đâu là chữ 🖱️?", options: [{ text: "CON CHUỘT", icon: "" }, { text: "CON CHUỘT", icon: "" }], answer: "CON CHUỘT", speechPrompt: "Đâu là chữ con chuột" },
        { question: "Đâu là chữ ⌨️?", options: [{ text: "BÀN PHÍM", icon: "" }, { text: "BAN PHÍM", icon: "" }], answer: "BÀN PHÍM", speechPrompt: "Đâu là chữ bàn phím" },
        { question: "Đâu là chữ 🧸?", options: [{ text: "GẤU BÔNG", icon: "" }, { text: "GẦU BÔNG", icon: "" }], answer: "GẤU BÔNG", speechPrompt: "Đâu là chữ gấu bông" },
        { question: "Đâu là chữ 🎈?", options: [{ text: "BÓNG BÂY", icon: "" }, { text: "BÓNG BAY", icon: "" }], answer: "BÓNG BAY", speechPrompt: "Đâu là chữ bóng bay" },
        { question: "Đâu là chữ 🪁?", options: [{ text: "CÁI GIỀU", icon: "" }, { text: "CÁI DIỀU", icon: "" }], answer: "CÁI DIỀU", speechPrompt: "Đâu là chữ cái diều" },
        { question: "Đâu là chữ 🚗?", options: [{ text: "Ô TÔ", icon: "" }, { text: "O TO", icon: "" }], answer: "Ô TÔ", speechPrompt: "Đâu là chữ ô tô" },
        { question: "Đâu là chữ 🚢?", options: [{ text: "TÀU THỦY", icon: "" }, { text: "TÀU THỦY", icon: "" }], answer: "TÀU THỦY", speechPrompt: "Đâu là chữ tàu thủy" },
        { question: "Đâu là chữ 🚂?", options: [{ text: "TÀU HỎA", icon: "" }, { text: "TÀU HÓA", icon: "" }], answer: "TÀU HỎA", speechPrompt: "Đâu là chữ tàu hỏa" },
        { question: "Đâu là chữ 🚲?", options: [{ text: "XE ĐẠP", icon: "" }, { text: "XẺ ĐẠP", icon: "" }], answer: "XE ĐẠP", speechPrompt: "Đâu là chữ xe đạp" },
        { question: "Đâu là chữ 🛴?", options: [{ text: "XE TRƯỢT", icon: "" }, { text: "XẺ TRƯỢT", icon: "" }], answer: "XE TRƯỢT", speechPrompt: "Đâu là chữ xe trượt" },
        { question: "Đâu là chữ 🚁?", options: [{ text: "TRƯỢT THĂNG", icon: "" }, { text: "TRỰC THĂNG", icon: "" }], answer: "TRỰC THĂNG", speechPrompt: "Đâu là chữ trực thăng" },
        { question: "Đâu là chữ 🚜?", options: [{ text: "MÁY CÀY", icon: "" }, { text: "MÀY CÀY", icon: "" }], answer: "MÁY CÀY", speechPrompt: "Đâu là chữ máy cày" },
        { question: "Đâu là chữ 🩺?", options: [{ text: "BÁC SĨ", icon: "" }, { text: "BAC SĨ", icon: "" }], answer: "BÁC SĨ", speechPrompt: "Đâu là chữ bác sĩ" }
    ]
};
